
>>> testIm = Image.open('RCoscillate.png')
>>> testCopyIm = testIm.copy()
>>> croppedIm = testIm.crop((200,100,300,150))
>>> testCopyIm.paste(croppedIm,(10,30)
		 )
>>> testCopyIm.paste(croppedIm,(100,200) )
>>> testCopyIm.save('pasted.png')
>>> croppedIm = testIm.crop((200,100,300,150))
>>> croppedIm.size
(100, 50)
>>> testCopyIm.paste(croppedIm,(1000,800) )
>>> testCopyIm.save('pasted.png')
>>> testCopyIm.paste(croppedIm,(1000,800) )
>>> testCopyIm.save('pasted.png')
>>> testIm = Image.open('pasted.png')
>>> 
>>> testIm.paste(croppedIm,(1000,800) )
>>> testIm.save('pasted2.png')
>>> testIm.paste(croppedIm,(600,800) )
>>> testIm.save('pasted3.png')
>>> testIm.paste(croppedIm,(600,400) )
>>> testIm.save('pasted3.png')
>>> testIm.save('pasted2.png')
>>> testIm.save('pasted4.png')
>>> testIm.paste(croppedIm,(200,400) )
>>> testIm.save('pasted2.png')
>>> testIm.save('pasted5.png')
>>> testIm.paste(croppedIm,(200,220) )
>>> testIm.save('pasted6.png')
>>> testIm.paste(croppedIm,(50,50) )
>>> testIm.save('pasted5.png')
>>> testIm.save('pasted6.png')
>>> testIm.paste(croppedIm,(50,80) )
>>> 
>>> testIm.save('pasted6.png')
>>> testIm.paste(croppedIm,(50,130) )
>>> testIm.save('pasted5.png')
>>> testIm.size
(435, 255)
